let list = [
  {
    _id: 1,
    title: '오일 퍼퓸 밤쉘 30ml',
    img: 'oil_01.jpg',
    price: '159,000',
    category: 'oil',
  },
  {
    _id: 2,
    title: '오일 퍼퓸 블루 세이지 블라썸 30ml',
    img: 'oil_02.jpg',
    price: '159,000',
    category: 'oil',
  },
  {
    _id: 3,
    title: '오일 퍼퓸 매그놀리아 힐 30ml',
    img: 'oil_03.jpg',
    price: '159,000',
    category: 'oil',
  },
  {
    _id: 4,
    title: '오일퍼퓸/핸드퍼퓸 10%OFF',
    img: 'oil_04.jpg',
    price: '54,000',
    category: 'oil',
  },
  {
    _id: 5,
    title: '오일 퍼퓸 2종 세트',
    img: 'oil_05.jpg',
    price: '108,000',
    category: 'oil',
  },
  {
    _id: 6,
    title: '오일 퍼퓸 밤쉘',
    img: 'oil_06.jpg',
    price: '54,000',
    category: 'oil',
  },
  {
    _id: 7,
    title: '오일 퍼퓸 트와일라잇 듀',
    img: 'oil_07.jpg',
    price: '54,000',
    category: 'oil',
  },
  {
    _id: 8,
    title: '오일 퍼퓸 포레스트 & 소울',
    img: 'oil_08.jpg',
    price: '54,000',
    category: 'oil',
  },
  {
    _id: 9,
    title: '오일 퍼퓸 블루 세이지 블라썸',
    img: 'oil_09.jpg',
    price: '54,000',
    category: 'oil',
  },
  {
    _id: 10,
    title: '오일 퍼퓸 4종 세트',
    img: 'oil_10.jpg',
    price: '172,000',
    category: 'oil',
  },
  {
    _id: 11,
    title: '핸드 퍼퓸 트루스 No.3',
    img: 'hand_01.jpg',
    price: '57,000',
    category: 'hand',
  },
  {
    _id: 12,
    title: '핸드 퍼퓸 트루스 No.2',
    img: 'hand_02.jpg',
    price: '57,000',
    category: 'hand',
  },
  {
    _id: 13,
    title: '핸드 퍼퓸 트루스 No.1',
    img: 'hand_03.jpg',
    price: '57,000',
    category: 'hand',
  },
  {
    _id: 14,
    title: '디퓨저 밤쉘',
    img: 'Difuser_01.jpg',
    price: '108,000',
    category: 'difuser',
  },
  {
    _id: 15,
    title: '디퓨저 포레스트&소울',
    img: 'Difuser_02.jpg',
    price: '108,000',
    category: 'difuser',
  },
  {
    _id: 16,
    title: '디퓨저 트와일라잇듀',
    img: 'Difuser_03.jpg',
    price: '108,000',
    category: 'difuser',
  },
  {
    _id: 17,
    title: '디퓨저 씨 모스',
    img: 'Difuser_04.jpg',
    price: '108,000',
    category: 'difuser',
  },
  {
    _id: 18,
    title: '디퓨저 블루 세이지 블라썸',
    img: 'Difuser_05.jpg',
    price: '108,000',
    category: 'difuser',
  },
  {
    _id: 19,
    title: '디퓨저 올리브 릿지',
    img: 'Difuser_06.jpg',
    price: '108,000',
    category: 'difuser',
  },
  {
    _id: 20,
    title: '디퓨저 리버 로렌',
    img: 'Difuser_07.jpg',
    price: '108,000',
    category: 'difuser',
  },
]

export default list;